image: python:latest

stages:
  - check
  - test


flake8:
  stage: check
  before_script:
    - pip install -U flake8
  script:
    - flake8

test:
  stage: test
  script:
    - python manage.py test
