FROM python:3.6

ENV PYTHONUNBUFFERED 1

#ENV C_FORCE_ROOT true

RUN mkdir /code
WORKDIR /code

RUN python -m pip install --upgrade pip

ADD requirements.txt /code/requirements.txt

RUN pip install -r requirements.txt

#COPY ./compose/django/start-dev.sh /start-dev.sh
#RUN sed -i 's/\r//' /start-dev.sh
#RUN chmod +x /start-dev.sh

ADD . /code/

CMD python manage.py collectstatic --no-input;python manage.py migrate; gunicorn eshop.wsgi -b 0.0.0.0:8000 & celery worker --app=eshop
